po/ca/system-monitor.po

Reviewed and ready to implement.

Catalan Translation

---

system-monitor@paradoxxx.zero.gmail.com/metadata.json

Looks like it's working fine with 3.16.

support for gnome 3.16

---

.gitignore
system-monitor@paradoxxx.zero.gmail.com/extension.js

Added fix for Gnome 3.18.2, thanks @franglais125.

---

system-monitor@paradoxxx.zero.gmail.com/extension.js

Added instructions for openSUSE when depending packages are not installed.

Added instructions for openSUSE

---

system-monitor@paradoxxx.zero.gmail.com/extension.js
system-monitor@paradoxxx.zero.gmail.com/stylesheet.css

Hello.
Suggested patch changes the layout as seen on the following screenshot:

Fix #290 (wrong font text-alignment).

---

po/ar/system-monitor.po
po/ca/system-monitor.po
po/cs/system-monitor.po
po/de/system-monitor.po
po/es_ES/system-monitor.po
po/es_MX/system-monitor.po
po/fa/system-monitor.po
po/fr/system-monitor.po
po/it/system-monitor.po
po/pl/system-monitor.po
po/pt/system-monitor.po
po/pt_BR/system-monitor.po
po/ro/system-monitor.po
po/ru/system-monitor.po
po/sk/system-monitor.po
po/system-monitor.pot
po/zh_CN/system-monitor.po

Hello,
After last commits in the upstream repository, I updated system-monitor.pot file, merged file system-monitor.po files and finally completed French translation file to reflect the changes in my own repository. This pull request is a proposition to review the changes I made, and eventually to update the upstream repository.
Feel free to make any comment about this.
Hope this is the right way to proceed as I'm not so familiar with github.
Cordially,
-- 
NVieville

Updated translations po files - completed french translation

---

po/fr/system-monitor.po

Please pull in this French translation update

French translation update

---

system-monitor@paradoxxx.zero.gmail.com/extension.js

This addresses issue #344 
Confirmation of the fix by @jwhipp, thanks!

Initialize units to Celsius or Fahrenheit.

---

system-monitor@paradoxxx.zero.gmail.com/metadata.json

Tested on my local machine with OpenSUSE Tumbleweed
@paradoxxxzero

Support gnome 3.26

---

po/ca/system-monitor.po

Fixed some errors and added the temperature threshold strings.

Updated strings in Catalan Translation

---

system-monitor@paradoxxx.zero.gmail.com/extension.js
system-monitor@paradoxxx.zero.gmail.com/prefs.js

@chrisspen Apologies, as you merged just now, I was finishing up fixing the warnings.
Let travis finish this one, and I'll check if all the warnings are clear.

Fix spacing to remove travis warnings.

---

po/pt/system-monitor.po

Sorry, there was a typo in #383 :disappointed:

po/pt/system-monitor.po: fix typo

---

system-monitor@paradoxxx.zero.gmail.com/extension.js

Hello,
This pull request do exactly what was provided in the patch in issue #400.
Cordially,
-- 
NVieville

Fix battery error and crash

---

system-monitor@paradoxxx.zero.gmail.com/extension.js
system-monitor@paradoxxx.zero.gmail.com/stylesheet.css

Hello all,
Here are two commits to fix the font scaling of the menu. Testing would be appreciated, in case I missed anything. But it's already much better, as we at least respond to scaling changes (requires session restart if you are testing).
Cheers

Fix font scaling

---

po/ru/system-monitor.po

Update Russian translation PO file.
Verified on Fedora 26, Gnome version 3.24.3 with Russian locale.

Update Russian translation PO file

---

system-monitor@paradoxxx.zero.gmail.com/metadata.json

I've just tested the version and it works fine.

Support GNOME 3.28.

---

.travis.yml

FIX: Update npm moved repository

Fix .travis.yml by updating npm installation precedure.

---

system-monitor@paradoxxx.zero.gmail.com/extension.js

Avoid accessing destroyed objects if menu or icon is disabled.
Should fix most of the Issue #464

extension.js: Updating battery, check prefs

---

system-monitor@paradoxxx.zero.gmail.com/extension.js

This fixes #496 for CPU [Freq.refresh]. BTW in the first commit you will find some fixes from jslint.

get rid of synchronous IO (read)

---

system-monitor@paradoxxx.zero.gmail.com/gpu_usage.sh

Signed-off-by: NVieville <nicolas.vieville@uphf.fr>

Fix typo nvidia-settings in gpu_usage.sh

---

README.md

Spell GNOME in uppercase instead of Gnome
Replace quotes by better ones
Add gnome-system-monitor to the list of packages needed
Add instructions to install on Mageia

Typographic fixes + update and fix install instructions

---

po/hu/system-monitor.po

As requested in #640, I have updated the translation with the new strings.

Add Hungarian translation

---

system-monitor@paradoxxx.zero.gmail.com/prefs.js

Fixed rendering of the thermal dropdown text in Gnome ~3.28.4 inspired by PR #674.

Fixed thermal sensor dropdown label rendering.

---

system-monitor@paradoxxx.zero.gmail.com/extension.js

In the CI travis run, eslint has a couple of suggestions for updates that will make it run cleanly.

Apply suggestions from eslint

---

system-monitor@paradoxxx.zero.gmail.com/extension.js
system-monitor@paradoxxx.zero.gmail.com/prefs.js

Hello,
I wonder if you could please merge this pull request to master branch. 
It contains 2 commits.
One to allow preferences window to be displayed (had to fix methods 
names for GtkBox according to https://gjs.guide/extensions/upgrading/gnome-shell-40.html#adding-to-the-containers).
The second one avoids extension warnings in gnome-shell journal (journalctl -qxe).
Feel free to make any comment about this subject.
Cordially,
-- 
NVieville

Gnome shell 40

---

system-monitor@paradoxxx.zero.gmail.com/metadata.json

Tested on openSUSE Tumbleweed.
Fixes #717.

Support Gnome 41.

---

system-monitor@paradoxxx.zero.gmail.com/metadata.json

Tested using my GNOME ppa with version gnome-shell 42~alpha and it works.

I can confirm that it works for GNOME 42~alpha

---

system-monitor@paradoxxx.zero.gmail.com/extension.js

Wrap into register class. Conditionally decode ByteArrays from files.

---

system-monitor@paradoxxx.zero.gmail.com/extension.js
system-monitor@paradoxxx.zero.gmail.com/metadata.json

Gnome-Shell 43 compatibility update.
