paradoxxxzero/gnome-shell-system-monitor-applet

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Probably there were 3 issues.
* sys mounts ('/home','/tmp','/boot','/usr','/usr/local') may have been added twice
* network mounts list is not complete. I see now that this is addressed also by #257, I am handling sshfs mounts
* as a partial workaround, one might think about removing disk load indicator. With this pull request, that workaround should work (only call refresh if the stats are shown somewhere)
Might be of interest of #202 #207 #235 #263
> Try to solve some issues about disk polling

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Do not recheck sys mounts, since this causes failure in loading (is_sys_mount expects a string, but mount is an object; there is no point in getting the mount path since the check was actually useless).
As per the net part, I added both is_native() and the additional filesystems mentioned in #257, since I wasn't able to test the filesystems involved.
The [is_native() documentation](https://developer.gnome.org/glibmm/stable/classGio_1_1File.html#aaa3b910bc9f240d4ebd0efc70979f163) states
> This (is_native() returning true) does not mean the file is local, as it might be on a locally mounted remote filesystem.
but also
>On some systems non-native files may be available using the native filesystem via a userspace filesystem (FUSE), in these cases this call will return false
So is_native() …
> Fix mount checks

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Well, I'm producing a bunch of pull request filled with errors to be fixed :) sorry
This one caused stats to be refreshed only if the stat was shown in both menu and applet. Now it's only needed to have it shown in one of them to trigger refresh.
> Fix check for visible item

- README.md
I had a problem with Gnome shell 3.16 and automatic install via extensions.gnome.org : extensions doesn't install and nothing in logs. I didn't searched a lot around and tried manual install.
After manual install procedure, extension wasn't enabled; I needed to enable it (via *https://extensions.gnome.org/local/* or *gnome-shell-extension-tool*), so adding it in manual install procedure seems to be a good idea, don't you think ?
> Fix manual install in 3.16: needs to enable extension with gnome-shell-extension-tool

- system-monitor@paradoxxx.zero.gmail.com/metadata.json
I've just tested the applet on openSUSE Tumbleweed with gnome 3.20.
> Enable Gnome 3.20

- system-monitor@paradoxxx.zero.gmail.com/extension.js
This allows the disk monitor to work with LVM. I tested it on my fairly complex setup(LVM with SSD cache, multiple partitions), and it seems to be pretty accurate. It also solves #277.
> Switched disk usage monitor to /proc/diskstats

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Concerning issue: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/279
This commit uses GiB as the unit for RAM and swap whenever the size is larger than 4GiB.
The threshold can obviously be changed (lines 1400 and 1641).
4GiB is maybe a low value, but when using something like ~16GiB of RAM, it is clearly more user friendly to have GiB as the unit.
Also, by default I use two decimal places. That could be adjusted as well.
> Use GiB instead of MiB when we have more than 4GiB of RAM (or swap)

- system-monitor@paradoxxx.zero.gmail.com/prefs.js
Common preferences of Cpu, Memory, etc appear in different orders, which I find a little annoying.
This patch should ensures that the first 2 horizontal layout boxes (which are most common) are ordered alphabetically by label.
Ie in all preference sections we'll have 'Display', then 'Show In Menu', then 'Show Text'.
Also added some simple readability improvements & style updates I believe are in accordance with the gnome style guide but I can change that if they don't match the project's style preferences.
> Fix preferences display order

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Declare GTop and NetworkManager outside of try-catch scope
Fixes #341
> Fix runtime error in GNOME 3.24

- po/system-monitor.pot
- system-monitor@paradoxxx.zero.gmail.com/extension.js
Hi,
This PR is a proposal to change
- `kbps` to `kbit/s`
- `Mbps` to `Mbit/s`
as the units shown when using the option "Show network speed in bits". This was originally proposed by @DevDef in issue #359.
The second commit in this PR is simply updating the general file for translations, so that it's easier to track strings that need to be translated.
> Use kbit/s instead of kbps

- system-monitor@paradoxxx.zero.gmail.com/extension.js
libnm-glib has been deprecated in favor of libnm for ages. GNOME Shell
seems to be among the last bits to be ported. This is now being done [1]:
[1] https://bugzilla.gnome.org/show_bug.cgi?id=789811
Unfortunately, due to GLib limitations, libnm-glib.so and libnm.so can't
be loaded at the same time and the attempt to do so results in a nasty
crash. The extensions thus needs to be updated to libnm.
> extension: make compatible with libnm

- system-monitor@paradoxxx.zero.gmail.com/extension.js
`/proc/cpuinfo` is deprecated, so this is now reading values from the `/sys` fs and then averaging the frequency of the cores instead of taking the last value.
Fixes #391
> Update CPU freqency to read from /sys fs

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Before:
After:
See the commits for more detailed information
> Improve disk list

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Fixes: #458
This closes the unwanted _stdin_ and _stderr_ file descriptors which if left unclosed will leak on each iteration.
Not sure if/that this is the most straightforward way of doing this in a GNOME Shell extension but it seems to work.  It does seem that there could/should be an easier way to close a file descriptor than using `Gio.DataInputStream()` and `Gio.UnixInputStream` but I'm not a GNOME Shell, nor even JS hacker.  Suggestions welcome.
> close unwanted file descriptors

- Makefile
To make reloading the extension easier when iterating on testing.
Signed-off-by: Brian J. Murrell <brian@interlinx.bc.ca>
> Add a Makefile target to reload the extension

- .travis.yml
I've extended our Travis-CI configuration to do a test installation of the extension into Gnome-Shell as well as ensure its CPU and memory usage doesn't exceed certain limits.
> Add gnome-shell install check to travis-ci config.

- .eslintrc
- system-monitor@paradoxxx.zero.gmail.com/extension.js
- system-monitor@paradoxxx.zero.gmail.com/metadata.json
- system-monitor@paradoxxx.zero.gmail.com/prefs.js
Finally after two nights, it works with the new gnome-shell 3.32:
* using ES6 classes (fixes: #508)
* `Shell.GenericContainer` converted to `Clutter.Actor` (#486)
* probably not compatible with non-ES6 gnome-shell
Evidence:
> Make it work with gnome-shell 3.32

- Makefile
This is v2 with suggestions from @brianjmurrell (v1 see #499).
````
$ make help
Install or remove (and reload) of the extension, for the local user
or as admin for all users:
make [install|remove]                        # for the local user
make DESTDIR=/ [install|remove] clean        # as admin for all users
Use environment VERSION=n.m to set verison string in the metadata and in
the generated zip-file explicit.  If no VERSION is passed, the current
commit SHA1 is used as version number in the metadata while the generated
zip file has no string attached.
Other targets are:
zip-file  - build and zip ./system-monitor@paradoxxx.zero.gmail.com.zip
reload    - reload extension system-monitor@paradoxxx.zero.gmail.com
clean     - remove most generated files
extension - rebuild …
```
> (v2) Makefile: complete rewrite with target 'help'

- README.md
Package `gir1.2-networkmanager-1.0` is not available.
> Update installation instructions for Ubuntu

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Fixes: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/564#issuecomment-612870009 
This is how I discovered the fix:
```bash
/usr/bin/gnome-shell-extension-prefs system-monitor
WARNING: Passing an extension UUID as a command-line argument to
gnome-shell-extension-prefs is deprecated.
In GNOME Shell extensions, use ExtensionUtils.openPrefs()
(sample code:
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/203)
In other modules, call the OpenExtensionPrefs D-Bus method instead.
Error: GDBus.Error:org.gnome.gjs.JSError.Error: Expected type filename for Argument 'path' but got type 'undefined'
```
> Fix: use latest way to call preferences

- system-monitor@paradoxxx.zero.gmail.com/metadata.json
“GNOME Shell” is the official spelling
“Information” is an uncountable noun in English: https://dictionary.cambridge.org/us/dictionary/english/information
Add battery and disk to the list of the information reported by the extension
> Fix “GNOME Shell” and “information” spelling

- README.md
Improve the README.md (fix remaining UTF-8 chars)
- Fix the removing of remaining apostrophes and UTF-8 chars (quotes and non-breaking spaces)
- Add Arch Linux install information for consistency with extension.js
- Remove information about outdated GNOME 3.0 and GNOME 3.2.
> Fix README.md (remove remaining Unicode chars...)

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Fixes: #633 by using `get_transformed_extents` only on mutter where it exists.
Tested on Ubuntu 18.04 and Ubuntu 21.04.
> Make tooltips show under the graph instead of the left of the screen

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Currently the display falls back to scientific notation, which isn't really that useful.
> Add units for network speeds over one gigabit

- system-monitor@paradoxxx.zero.gmail.com/extension.js
We pass GLib.PRIORITY_DEFAULT_IDLE as priority to Mainloop to avoid
micro-freezes of the Shell. This is mostly visible in Wayland sessions.
> Prevent refreshes while the Shell is busy.

- system-monitor@paradoxxx.zero.gmail.com/gpu_usage.sh
egrep is considered non-standard and deprecated, and it is recommended
to use grep -E instead.
> gpu_usage.sh: Used grep -E instead of egrep

- system-monitor@paradoxxx.zero.gmail.com/extension.js
avoids NaNs being displayed in widget when script returns unexpected values (e.g GPU is powered down etc)
> sanitize usage vals parsed from gpu_usage.sh script

- system-monitor@paradoxxx.zero.gmail.com/prefs.js
Preferences are not run in the shell context and should use GTK instead of Clutter.
They actually do but the import was forgotten here.
> prefs: Remove unused Clutter reference

- system-monitor@paradoxxx.zero.gmail.com/gpu_usage.sh
From bash's man page: "the exit status of a function is the exit
status of the last command executed in the body".
> gpu_usage.sh: Remove superfluous function return statement

- system-monitor@paradoxxx.zero.gmail.com/gpu_usage.sh
It is recommended to use $() over the legacy ``.
See e.g.
https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xcu_chap02.html#tag_23_02_06_03
Also removed the quotes that are not needed when assigning variables.
> gpu_usage.sh: Use contemporary $() instead of legacy ``

- system-monitor@paradoxxx.zero.gmail.com/prefs.js
Similarly as described in the linked issues, on my machine there are 9 chips:
```bash
andrzej:/sys/class/hwmon$ ls
hwmon0  hwmon1  hwmon2  hwmon3  hwmon4  hwmon5  hwmon6  hwmon7  hwmon8
```
Moreover, my machine is a hexa-core and so, chip `hwmon6` provides access to 7 temperature sensors (1 for the whole package + 6 for each core):
```bash
andrzej:/sys/class/hwmon/hwmon6$ ls temp*_input
temp1_input  temp2_input  temp3_input  temp4_input  temp5_input  temp6_input  temp7_input
```
Sensors are correctly reported by `sensors` utility:
```bash
andrzej:~$ sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +41.0°C  
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +47.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +47.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1: …
```
> Sensor scanning improvements

- system-monitor@paradoxxx.zero.gmail.com/gpu_usage.sh
The sed command that changes ', ' from the `nvidia-smi` output with
newlines can be replaced with shell built-in functionality.
> gpu_usage.sh: Use faster shell internals instead of sed

- system-monitor@paradoxxx.zero.gmail.com/gpu_usage.sh
Using /bin/sh instead of bash will make this script run much more
lightweight on hosts with e.g. Debian-based systems that uses dash for
/bin/sh which is ~10% the footprint of bash.
> gpu_usage.sh: Make POSIX compatible and use /bin/sh

- Dockerfile.ubuntu2004
- run-docker.sh
- testing/run_gui_tests.sh
- testing/test_gui.py
Closes #663.
The [dogtail](https://gitlab.com/dogtail/dogtail) test tool is used to write the tests as suggested in the linked issue.
The tests run inside the docker image, steps:
```shell
./build-docker.sh
./run-docker.sh
./open-docker.sh
cd /home/default/shared
./run_gui_tests.sh
./close-docker.sh
```
> Add GUI testing proof-of-concept

- system-monitor@paradoxxx.zero.gmail.com/extension.js
- system-monitor@paradoxxx.zero.gmail.com/metadata.json
- system-monitor@paradoxxx.zero.gmail.com/prefs.js
Hopefully addreses #672 
Gtk4 introduced breaking changes to how the preferences are created. This PR seeks to handle those changes while maintaining backwards compatibility
-  Gtk.HBox and Gtk.VBox are dead, replaced with Gtk.Box with orientation 
- `border_width` is dead, replace it with margins of 10 (this seems to function similarly)
- `add`, `pack_start`, `pack_end` calls for Box have been replaced with `append` and `prepend`: these calls are aliased where appropriate
- Because packing is gone, spacing is now controlled by `set_homogeneous`; It has bigger windows and boxes, but seems to be the closest to maintaining packing?
- `show_all` is unneeded in new versions
- `get_all_children` is gone, so I use effectively an iterator to build and sort the array
Additionally fixes complaints …
> update prefs to support gnome 40

- README.md
Without clutter I couldn't open the preferences
Fixes: `Error: Requiring Clutter ...`
Tested with master branch and GS 40
> Require clutter for Arch Linux

- system-monitor@paradoxxx.zero.gmail.com/prefs.js
There is a strict distinction between GNOME Shell using the Clutter toolkit and apps (including extension preferences) using GTK.
And while it is technically possible for apps to use Clutter, the library is unmaintained and its use is discouraged. Additionally, GNOME Shell actually uses its own internal fork of Clutter so if we depend on Clutter, we need to install a second copy of it just for the preferences.
Fortunately, GDK 4 [supports parsing hex colours with alpha values](https://gitlab.gnome.org/GNOME/gtk/merge_requests/2356), so we can just use it directly without depending on Clutter.
We will only use the Compat module when GTK 4 is not available, such as on GNOME < 40.
> prefs: Remove clutter dependency on GNOME 40

- system-monitor@paradoxxx.zero.gmail.com/extension.js
- Don't use compatibility characters for temperature symbols. See of https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/562 and https://stackoverflow.com/a/10799833/3025505.
- Don't convert to Fahrenheit until showing as text. For the graphs it doesn't matter which unit the values are in, as long as all the values are in the same unit. See https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/571.
- Update temperature unit in menu. Fixes https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/571.
- Remove obsolete comment, since there is a max value of 100°C introduced in https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/commit/be41d9c42499e6c2c5b4ea56e3034fdc3698d694.
Should also fix …
> Small fixes to thermal monitoring

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Not all parts of the interface follow the display scale setting on a high dpi monitor. Text is scaled automatically, but the graphs, pie chart and bar chart remained tiny.
This is my attempt to have those elements use the right scale factor. It is only read once, you have to restart the extension or Gnome Shell after changing the monitor scale factor.
(Also, this is my first time touching Javascript and Gnome Shell extensions.)
This should fix https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/525, although that issue is a bit vague. Fixes https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/613.
> Add support for display scale factor

- system-monitor@paradoxxx.zero.gmail.com/README
`libgtop` is already needed by `gnome-system-monitor` and therefore be removed from the list
> remove redundant dependency

- archlinux/PKGBUILD
With the `git://` url, mkpkg would fail with
```
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
Changing the url to an https one lets the package build successfully.
> Fix git error in PKGBUILD

- test.sh
This should make build logs less confusing
https://stackoverflow.com/questions/107705/disable-output-buffering
> Disable Python output buffering

- system-monitor@paradoxxx.zero.gmail.com/extension.js
- system-monitor@paradoxxx.zero.gmail.com/prefs.js
- system-monitor@paradoxxx.zero.gmail.com/schemas/org.gnome.shell.extensions.system-monitor.gschema.xml
Resolves https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/770.
And make it 0 by default rather than 500ms.
The row of general settings is getting long - it might be good to break it up over a couple of rows.
> Add setting for tooltip delay

- system-monitor@paradoxxx.zero.gmail.com/prefs.js
Resolves https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/769
> Remove "nvidia gpu only" message

- system-monitor@paradoxxx.zero.gmail.com/gpu_usage.sh
The use of cut and gawk in the script can easily be replaced with basic
POSIX shell script internal parameter expansion functionality. The
benefit of this is portability, since there are no longer dependencies
on cut and gawk. (And as a bonus, execution of the script gets more
lightweight.)
> gpu_usage.sh: Replace cut and gawk with shell internals

- system-monitor@paradoxxx.zero.gmail.com/extension.js
Fix a small typo in the Disk menu. There was a missing space between /s and R.
> Fix a small typo in extension.js

- system-monitor@paradoxxx.zero.gmail.com/extension.js
- system-monitor@paradoxxx.zero.gmail.com/metadata.json
- system-monitor@paradoxxx.zero.gmail.com/prefs.js
- system-monitor@paradoxxx.zero.gmail.com/schemas/org.gnome.shell.extensions.system-monitor.gschema.xml
Resolves https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/329. Resolves https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/624. On Gnome Shell 42+, that is.
This change allow the extension to continue running while the screen is locked, in an officially-supported manner - by making use of the new [session modes feature introduced in Gnome Shell 42](https://gjs.guide/extensions/topics/session-modes.html). This is as opposed to the frowned-upon approach of disabling the `disable()` function (as [implemented](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/329#issuecomment-377823916) by @franglais125), which would apparently prevent publishing to the Gnome Extensions website, and also mean the user can't turn off the …
> Continue running when screen is locked and optionally show on lockscreen, using session modes
